language: python
sudo: false
python:
- pypy
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install tox-travis flake8 collective.checkdocs Pygments
script:
- flake8 .
- python setup.py checkdocs
- tox
after_success:
- bash <(curl -s https://codecov.io/bash)
